#!/usr/bin/env bash
# This script manages the process that writes "I am alive!" to /tmp/my_process indefinitely.

if [ "$1" == "start" ]; then
    nohup bash -c 'while true; do echo "I am alive!" > /tmp/my_process; sleep 2; done' &
    echo $! > /var/run/my_process.pid
    echo "manage_my_process started"
elif [ "$1" == "stop" ]; then
    kill $(cat /var/run/my_process.pid)
    rm -f /var/run/my_process.pid
    echo "manage_my_process stopped"
elif [ "$1" == "restart" ]; then
    kill $(cat /var/run/my_process.pid)
    rm -f /var/run/my_process.pid
    nohup bash -c 'while true; do echo "I am alive!" > /tmp/my_process; sleep 2; done' &
    echo $! > /var/run/my_process.pid
    echo "manage_my_process restarted"
else
    echo "Usage: manage_my_process {start|stop|restart}"
fi
